"""Export the Adventurer's .blend to web/js/adventurer-mesh.js (Plans/tweede-avonturier.md).

Run by build-adventurer.py at its end; also runnable on its own over an open
assets/adventurer/island-adventurer.blend. Writes the same shape web/js/settler-mesh.js has -
parts with a slot, a variant, a limb group, corner normals and, on a limb, two skin weights
per corner (bend, end: the root takes the rest) - plus `colors` on the body's own parts, the
texture sampled per corner, which avatar.js uses in place of a slot colour.
"""
import bpy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
scene = bpy.context.scene
parts = []
for o in sorted(bpy.data.objects, key=lambda x: x.name):
    if o.type != 'MESH' or 'avatar_group' not in o:
        continue
    mesh = o.data
    mesh.calc_loop_triangles()
    p = dict(name=o.name, slot=o['avatar_slot'], variant=o['avatar_variant'], group=o['avatar_group'],
             positions=[], normals=[])
    attr = mesh.color_attributes.get('Colour')
    if attr:
        p['colors'] = []
    group = o.get('avatar_skin')
    names = {g.index: g.name for g in o.vertex_groups}
    if group:
        p.update(skinGroup=group, skin=[])
    normal_matrix = o.matrix_world.to_3x3().inverted().transposed()
    for tri in mesh.loop_triangles:
        for idx, loop in zip(tri.vertices, tri.loops):
            v = o.matrix_world @ mesh.vertices[idx].co
            n = (normal_matrix @ mesh.corner_normals[loop].vector).normalized()
            p['positions'] += [round(x, 6) for x in (v.x, v.z, -v.y)]
            p['normals'] += [round(x, 4) for x in (n.x, n.z, -n.y)]
            if attr:
                p['colors'] += [round(x, 3) for x in attr.data[loop].color[:3]]
            if group:
                weights = {names[g.group]: g.weight for g in mesh.vertices[idx].groups}
                p['skin'] += [round(weights.get(group + ':' + str(i), 0), 4) for i in (1, 2)]
    parts.append(p)
if not parts:
    raise RuntimeError('Open assets/adventurer/island-adventurer.blend before exporting.')
data = {
    'ADVENTURER_EYE_Y': scene['adventurer_eye_y'],
    'ADVENTURER_RIG': json.loads(scene['adventurer_rig']),
    'ADVENTURER_JOINTS': json.loads(scene['adventurer_joints']),
    'ADVENTURER_PARTS': parts,
}
(ROOT / 'web/js/adventurer-mesh.js').write_text(
    '// Generated by scripts/export-adventurer.py in Blender. Do not edit.\n'
    + ''.join('export const ' + key + ' = ' + json.dumps(value, separators=(',', ':')) + ';\n' for key, value in data.items()),
    encoding='utf8', newline='\n')
print('Exported adventurer', sum(len(p['positions']) // 9 for p in parts), 'triangles')
