"""Bake the Blender model sets to native island parts.

    blender --background --python scripts/export-models.py               every set
    blender --background --python scripts/export-models.py -- props      only these

or, from an authoring script with the scene still in memory, through runpy with
`init_globals={'MODEL_SET': 'props'}` - which is what scripts/build-props.py and
scripts/export-tavern.py do, so that building a set and baking it are one run.

A set is one .blend under assets/<set>/ and becomes web/js/<set>-mesh.js: a plain module
of triangles, vertex colours and a sheet tag per part, which buildings.js mesh() turns
back into a part indistinguishable from a box(). No glTF, no loader, nothing to wait for
on the boot path - the same route the settlers already take.

What the conventions are and why is written down in assets/README.md. What is allowed -
sheet names, triangle budgets, anchor names, origin on the ground - is decided by
scripts/model-rules.mjs after this script has run; `npm run models` does both and fails
on either. This file bakes what it is given and only refuses what it cannot express.
"""
import bpy
import json
import sys
from pathlib import Path
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[1]
# The figures are their own spoor: assets/settler/*.blend carries avatar_slot tags and is
# baked to settler-mesh.js / villager-mesh.js by scripts/export-settler.py.
SKIP = {'settler'}
# The material name prefixes this can turn into a sheet id, and the collection name
# prefixes that mark an asset. Kept here because the bake cannot proceed without knowing
# either; scripts/model-rules.mjs is where both live for everyone else, and it checks the
# result again once this has run.
# `bark` and `foliage` are the last two: sheets of the island's own that no building is
# drawn on. A tree wears them as a material each, off one geometry with a group apiece,
# which is what an InstancedMesh with a material array needs - see grouped() in
# web/js/models.js. A building has one material and cannot use them.
SHEETS = ['plain', 'wall', 'roof', 'stone', 'plank', 'plankZ', 'ground', 'bark', 'foliage']
CLASSES = ('house_', 'roof_', 'addon_', 'prop_', 'civic_', 'flora_', 'fauna_')
# web/js/tavern-mesh.js was written by the hand-rolled exporter this script generalises,
# and re-baking it here has to leave the file byte for byte the way it was: that identity
# is the only proof that generalising the exporter moved no vertex of the tavern. The
# first line is the one thing about the file that is not geometry, so the tavern keeps the
# line it was first baked with and everything else gets the line below it.
BANNER = {'tavern': '// Generated by Blender scripts/export-tavern.py.\n'}


def game(p):
    """Blender is Z up and the island is Y up, with the front of a model facing +Z."""
    return [round(p.x, 6), round(p.z, 6), round(-p.y, 6)]


def asset_of(obj):
    """Which asset an object belongs to: a collection whose name says what class it is.

    A .blend whose objects sit loose - in the scene collection, or in the `Collection`
    Blender starts every file with - is a single hero asset: the tavern is one building
    and every part of it belongs to that building. A set that holds several things puts
    each in a collection called `prop_barrel` or `roof_gable_a`, and every part inside
    has to carry that name too, so a part name stays unique across every set the
    register holds. The prefix is what tells a budget from a folder somebody made to
    tidy up in.
    """
    for c in obj.users_collection:
        if c.name.startswith(CLASSES):
            return c.name
    return None


def bake(set_name, source):
    scene = bpy.context.scene
    deps = bpy.context.evaluated_depsgraph_get()
    parts, anchors, assets = {}, {}, {}

    for obj in scene.objects:
        asset = asset_of(obj)
        if asset is not None:
            assets.setdefault(asset, {'parts': [], 'anchors': {}})
        if obj.type == 'EMPTY' and obj.name.startswith('anchor.'):
            where = assets[asset]['anchors'] if asset is not None else anchors
            where[obj.name.split('.', 1)[1]] = game(obj.matrix_world.translation)
        if obj.type != 'MESH' or not obj.get('building_part'):
            continue
        if asset is not None and not obj.name.startswith(asset):
            raise ValueError(f'{set_name}: "{obj.name}" is in collection "{asset}" but is not named after it')
        evaluated = obj.evaluated_get(deps)
        mesh = evaluated.to_mesh()
        mesh.calc_loop_triangles()
        origin = obj.matrix_world.translation
        # Preserve CORNER/POINT vertex colours painted by hand in Blender when present.
        attr = mesh.color_attributes.active_color
        for slot, material in enumerate(obj.data.materials):
            if not material:
                continue
            sheet = material.name.split(':', 1)[0]
            if sheet not in SHEETS:
                raise ValueError(f'{set_name}: material "{material.name}" names no sheet; use one of ' + ', '.join(SHEETS))
            positions = []
            colors = []
            for tri in mesh.loop_triangles:
                if tri.material_index != slot:
                    continue
                points = [Vector(game(obj.matrix_world @ mesh.vertices[i].co - origin)) for i in tri.vertices]
                if (points[1] - points[0]).cross(points[2] - points[0]).length_squared < 1e-16:
                    continue
                for j, p in enumerate(points):
                    positions.extend(round(v, 6) for v in p)
                    color = attr.data[tri.loops[j] if attr.domain == 'CORNER' else tri.vertices[j]].color if attr else material.diffuse_color
                    colors.extend(round(v, 6) for v in color[:3])
            if positions:
                name = obj.name if len(obj.data.materials) == 1 else f'{obj.name}:{slot}'
                if name in parts:
                    raise ValueError(f'{set_name}: two parts are called "{name}"')
                parts[name] = {'positions': positions, 'colors': colors, 'sheet': sheet,
                               'emissive': float(material.get('emissive', 0)), 'at': game(origin)}
                if asset is not None:
                    assets[asset]['parts'].append(name)
        evaluated.to_mesh_clear()

    if not parts:
        raise ValueError(f'{set_name}: no building_part meshes in {source.name}')
    if 'building_height' not in scene:
        raise ValueError(f'{set_name}: the scene has no building_height')

    # `assets` is left out entirely when the .blend names none, which keeps a hero set's
    # module exactly what it was before sets could hold more than one thing.
    result = {'parts': parts, 'anchors': anchors, 'height': float(scene['building_height'])}
    if assets:
        result['assets'] = assets
    target = ROOT / 'web/js' / f'{set_name}-mesh.js'
    banner = BANNER.get(set_name, f'// Generated by Blender scripts/export-models.py from assets/{set_name}/{source.name}.\n')
    target.write_text(
        banner + f'export const {set_name.upper()} = ' + json.dumps(result, separators=(',', ':')) + ';\n',
        encoding='utf8')
    tris = sum(len(p['positions']) // 9 for p in parts.values())
    print(f'baked {set_name}: {len(parts)} parts, {tris} triangles, '
          f'{len(assets) or 1} asset(s) -> web/js/{target.name}')
    return target


def blend_of(set_dir):
    """The one .blend in a set's folder. Two would make the source ambiguous."""
    found = sorted(set_dir.glob('*.blend'))
    if len(found) != 1:
        raise ValueError(f'{set_dir.name}: expected one .blend in {set_dir}, found {len(found)}')
    return found[0]


def model_sets():
    """Every set there is: a folder under assets/ with one .blend in it."""
    return sorted(d.name for d in (ROOT / 'assets').iterdir()
                  if d.is_dir() and d.name not in SKIP and list(d.glob('*.blend')))


# scripts/preview-model.py runs this file with HELPERS_ONLY to borrow asset_of() and the
# rest, rather than keeping a second copy of the rule that decides what an asset is.
if globals().get('HELPERS_ONLY'):
    pass
# Baking the scene that is already open, for an authoring script that has just built it.
elif globals().get('MODEL_SET'):
    IN_PLACE = globals()['MODEL_SET']
    bake(IN_PLACE, blend_of(ROOT / 'assets' / IN_PLACE))
else:
    wanted = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    sets = model_sets()
    if wanted:
        unknown = [s for s in wanted if s not in sets]
        if unknown:
            raise ValueError('no such model set: ' + ', '.join(unknown))
        sets = [s for s in sets if s in wanted]
    for name in sets:
        source = blend_of(ROOT / 'assets' / name)
        bpy.ops.wm.open_mainfile(filepath=str(source))
        bake(name, source)
