"""Bake the saved Blender tavern to native parts; material prefix is its sheet tag."""
import bpy
import json
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[1]
parts={}; anchors={}
deps=bpy.context.evaluated_depsgraph_get()
def game(p):return [round(p.x,6),round(p.z,6),round(-p.y,6)]
for obj in bpy.context.scene.objects:
    if obj.type=='EMPTY' and obj.name.startswith('anchor.'):
        anchors[obj.name.split('.',1)[1]]=game(obj.matrix_world.translation)
    if obj.type!='MESH' or not obj.get('building_part'):continue
    evaluated=obj.evaluated_get(deps);mesh=evaluated.to_mesh();mesh.calc_loop_triangles()
    origin=obj.matrix_world.translation
    # Preserve CORNER/POINT vertex colours painted by hand in Blender when present.
    attr=mesh.color_attributes.active_color
    for slot,material in enumerate(obj.data.materials):
        if not material:continue
        sheet=material.name.split(':',1)[0]
        if sheet not in ['plain','wall','roof','stone','plank','plankZ']:raise ValueError('Unknown sheet '+sheet)
        positions=[];colors=[]
        for tri in mesh.loop_triangles:
            if tri.material_index!=slot:continue
            points=[Vector(game(obj.matrix_world@mesh.vertices[i].co-origin)) for i in tri.vertices]
            if (points[1]-points[0]).cross(points[2]-points[0]).length_squared<1e-16:continue
            for j,p in enumerate(points):
                positions.extend(round(v,6) for v in p)
                color=attr.data[tri.loops[j] if attr.domain=='CORNER' else tri.vertices[j]].color if attr else material.diffuse_color
                colors.extend(round(v,6) for v in color[:3])
        if positions:
            name=obj.name if len(obj.data.materials)==1 else f'{obj.name}:{slot}'
            parts[name]={'positions':positions,'colors':colors,'sheet':sheet,'emissive':float(material.get('emissive',0)), 'at':game(origin)}
    evaluated.to_mesh_clear()
if not parts:raise ValueError('No building parts: open agentvillage-tavern.blend first')
result={'parts':parts,'anchors':anchors,'height':float(bpy.context.scene['building_height'])}
(ROOT/'web/js/tavern-mesh.js').write_text('// Generated by Blender scripts/export-tavern.py.\nexport const TAVERN = '+json.dumps(result,separators=(',',':'))+';\n',encoding='utf8')
print('Tavern:',len(parts),'parts,',sum(len(p['positions'])//9 for p in parts.values()),'triangles')
