"""Export the open settler .blend after editing; includes hidden hat variants."""
import bpy
import json
from pathlib import Path
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[1]
deps = bpy.context.evaluated_depsgraph_get()
data, colors = [], {}
for obj in bpy.context.scene.objects:
    if obj.type != 'MESH' or 'avatar_slot' not in obj:
        continue
    slot = obj['avatar_slot']
    rgb = obj.data.materials[0].diffuse_color[:3]
    srgb = [round(255 * (12.92*v if v <= .0031308 else 1.055*v**(1/2.4)-.055)) for v in rgb]
    colors[slot] = (srgb[0] << 16) | (srgb[1] << 8) | srgb[2]
    evaluated = obj.evaluated_get(deps)
    mesh = evaluated.to_mesh()
    mesh.calc_loop_triangles()
    positions = []
    for tri in mesh.loop_triangles:
        points = []
        for i in tri.vertices:
            p = obj.matrix_world @ mesh.vertices[i].co
            points.append(Vector(tuple(round(v, 6) for v in (p.x, p.z, -p.y))))
        if (points[1]-points[0]).cross(points[2]-points[0]).length_squared > 1e-20:
            for p in points:
                positions.extend(round(v, 6) for v in p)
    data.append(dict(name=obj.name, slot=slot, variant=obj['avatar_variant'], positions=positions))
    evaluated.to_mesh_clear()
if not data:
    raise RuntimeError('Open assets/settler/agentvillage-settler.blend before exporting.')
mesh_name = bpy.context.scene.get('avatar_mesh_name', 'settler-mesh.js')
if mesh_name not in ('settler-mesh.js', 'villager-mesh.js'):
    raise RuntimeError('Unknown avatar mesh output')
target = ROOT / 'web/js' / mesh_name
target.write_text('// Generated by scripts/export-settler.py in Blender. Do not edit vertices by hand.\n'
    + 'export const SETTLER_EYE_Y = ' + str(bpy.context.scene.get('avatar_eye_y', .383)) + ';\n'
    + 'export const SETTLER_COLORS = ' + json.dumps(colors, separators=(',',':')) + ';\n'
    + 'export const SETTLER_PARTS = ' + json.dumps(data, separators=(',',':')) + ';\n', encoding='utf8')
print('Exported', sum(len(p['positions'])//9 for p in data), 'triangles across all hat variants to', target)
