# Promptholm seen from Godot. The island is not shipped in village.json -- only its seed
# is -- so the ground here is generated by the same rules as the browser viewer, out of
# scripts/terrain.gd, and checked against island.terrainHash before anything is drawn.
extends Node3D

const SERVER := "http://localhost:4747"
const REFRESH_SECONDS := 5.0
const WALK_SPEED := 14.0
const LOOK_SPEED := 0.005

const SEASONS := {
	"spring": { "meadow": Color8(0x93, 0xcf, 0x62), "upland": Color8(0x74, 0xad, 0x4c), "summit": Color8(0xa3, 0x9d, 0x90) },
	"summer": { "meadow": Color8(0x8f, 0xbf, 0x5a), "upland": Color8(0x6f, 0xa6, 0x4a), "summit": Color8(0xa3, 0x9d, 0x90) },
	"autumn": { "meadow": Color8(0x91, 0xad, 0x68), "upland": Color8(0x73, 0x8b, 0x53), "summit": Color8(0xa3, 0x9d, 0x90) },
	"winter": { "meadow": Color8(0x8f, 0x9f, 0x76), "upland": Color8(0x77, 0x85, 0x5f), "summit": Color8(0xe6, 0xe6, 0xe0) },
}

var camera: Camera3D
var status: Label
var ground_root: Node3D
var water_root: Node3D
var objects_root: Node3D

var player := Vector3(0.0, 26.0, 44.0)
var yaw := 0.0
var pitch := -0.5
var dragging := false

var terrain: PmTerrain
var village := {}
var props_data := []
var requests_left := 0
var last_signature := ""
var materials := {}

# The surface actually drawn: the model heightfield sampled finer and then smoothed.
# Everything that stands on the ground is placed on this, so a house sits on what
# you can see rather than on what the layout happens to average to.
var _fine := PackedFloat32Array()
var _fine_cols := 0
var _fine_step := 1.0

func _ready() -> void:
	_build_shell()
	_make_materials()
	_fetch_world()
	_update_camera()
	var timer := Timer.new()
	timer.wait_time = REFRESH_SECONDS
	timer.timeout.connect(_fetch_world)
	add_child(timer)
	timer.start()

func _process(delta: float) -> void:
	var input := Vector2.ZERO
	if Input.is_key_pressed(KEY_W): input.y -= 1.0
	if Input.is_key_pressed(KEY_S): input.y += 1.0
	if Input.is_key_pressed(KEY_A): input.x -= 1.0
	if Input.is_key_pressed(KEY_D): input.x += 1.0
	if Input.is_key_pressed(KEY_Q): player.y += WALK_SPEED * delta
	if Input.is_key_pressed(KEY_E): player.y -= WALK_SPEED * delta
	if input.length() > 1.0: input = input.normalized()
	var speed := WALK_SPEED * (3.0 if Input.is_key_pressed(KEY_SHIFT) else 1.0)
	var forward := Vector3(sin(yaw), 0.0, -cos(yaw))
	var right := Vector3(cos(yaw), 0.0, sin(yaw))
	player += (right * input.x + forward * -input.y) * speed * delta
	# Never sink through the ground: the island has a hill four units up and a river bed
	# below the sea, so a fixed floor would either clip the summit or swim.
	var floor_y := 1.6
	if terrain != null:
		floor_y = _render_height(player.x, player.z) + 1.6
	player.y = maxf(player.y, floor_y)
	_update_camera()

func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT:
		dragging = event.pressed
		return
	if event is InputEventMouseMotion and dragging:
		yaw -= event.relative.x * LOOK_SPEED
		pitch = clampf(pitch - event.relative.y * LOOK_SPEED, -1.35, 0.6)
		_update_camera()

func _update_camera() -> void:
	camera.position = player
	camera.rotation = Vector3(pitch, yaw, 0.0)

func _build_shell() -> void:
	ground_root = Node3D.new()
	ground_root.name = "Ground"
	add_child(ground_root)
	water_root = Node3D.new()
	water_root.name = "Water"
	add_child(water_root)
	objects_root = Node3D.new()
	objects_root.name = "Objects"
	add_child(objects_root)

	camera = Camera3D.new()
	camera.fov = 60.0
	camera.far = 2000.0
	add_child(camera)

	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-48, -35, 0)
	sun.light_energy = 1.25
	sun.light_color = Color8(0xff, 0xf4, 0xe0)
	sun.shadow_enabled = true
	add_child(sun)

	var env := WorldEnvironment.new()
	var e := Environment.new()
	var sky_mat := ProceduralSkyMaterial.new()
	sky_mat.sky_top_color = Color8(0x4e, 0x8f, 0xd4)
	sky_mat.sky_horizon_color = Color8(0xcf, 0xe4, 0xf5)
	sky_mat.ground_bottom_color = Color8(0x35, 0x4a, 0x52)
	sky_mat.ground_horizon_color = Color8(0xcf, 0xe4, 0xf5)
	var sky := Sky.new()
	sky.sky_material = sky_mat
	e.background_mode = Environment.BG_SKY
	# Without a tonemapper the sand and the summit blow out to white under a bright sky.
	e.tonemap_mode = Environment.TONE_MAPPER_FILMIC
	e.tonemap_white = 1.3
	e.sky = sky
	e.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	e.ambient_light_energy = 0.32
	e.fog_enabled = true
	e.fog_light_color = Color8(0xa8, 0xc4, 0xd8)
	e.fog_density = 0.0006
	env.environment = e
	add_child(env)

	var canvas := CanvasLayer.new()
	add_child(canvas)
	status = Label.new()
	status.position = Vector2(18, 14)
	status.text = "Loading Promptholm..."
	status.add_theme_font_size_override("font_size", 18)
	status.add_theme_color_override("font_color", Color(0.95, 0.99, 0.95))
	status.add_theme_color_override("font_outline_color", Color(0, 0, 0, 0.8))
	status.add_theme_constant_override("outline_size", 6)
	canvas.add_child(status)

func _mat(color: Color, roughness: float = 0.95) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	m.roughness = roughness
	return m

func _make_materials() -> void:
	materials.ground = StandardMaterial3D.new()
	materials.ground.vertex_color_use_as_albedo = true
	# Colour8() gives sRGB values; without this Godot reads them as linear and the
	# meadow comes out bleached almost white.
	materials.ground.vertex_color_is_srgb = true
	materials.ground.roughness = 0.96
	materials.water = StandardMaterial3D.new()
	materials.water.vertex_color_use_as_albedo = true
	materials.water.vertex_color_is_srgb = true
	materials.water.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	materials.water.roughness = 0.12
	materials.water.metallic = 0.25
	materials.water.cull_mode = BaseMaterial3D.CULL_DISABLED
	materials.ocean = _mat(Color8(0x0d, 0x31, 0x4a), 0.14)
	materials.ocean.metallic = 0.3
	materials.path = _mat(Color8(0x9d, 0x8c, 0x6e))
	materials.paved = _mat(Color8(0x8d, 0x88, 0x7c))
	materials.wall = _mat(Color8(0xd8, 0xc6, 0xa4))
	materials.roof = _mat(Color8(0xa5, 0x52, 0x36))
	materials.civic_wall = _mat(Color8(0xe4, 0xd8, 0xb4))
	materials.civic_roof = _mat(Color8(0x6d, 0x7f, 0x8c))
	materials.shed = _mat(Color8(0x9a, 0x7c, 0x57))
	materials.shed_roof = _mat(Color8(0x6e, 0x5a, 0x42))
	materials.deck = _mat(Color8(0x8a, 0x6a, 0x46))
	materials.rail = _mat(Color8(0x6b, 0x50, 0x36))
	materials.trunk = _mat(Color8(0x5a, 0x40, 0x2c))
	materials.leaf = _mat(Color8(0x2f, 0x6b, 0x31))
	materials.lamp = _mat(Color8(0xff, 0xd4, 0x7a))
	materials.dark = _mat(Color8(0x2d, 0x22, 0x18))
	materials.panel = _mat(Color8(0xe8, 0xec, 0xe4))
	materials.active = _mat(Color8(0xff, 0xc8, 0x54))

# ---- data -------------------------------------------------------------------

func _fetch_world() -> void:
	if requests_left > 0:
		return
	requests_left = 2
	_http(SERVER + "/village.json?ts=" + str(Time.get_ticks_msec()), _on_village)
	_http(SERVER + "/api/props", _on_props)

func _http(url: String, callback: Callable) -> void:
	var req := HTTPRequest.new()
	# Without a timeout HTTPRequest sits in connecting forever when nothing is
	# listening, so requests_left never reaches zero and the sample island -- the whole
	# point of having one -- is never reached.
	req.timeout = 5.0
	add_child(req)
	req.request_completed.connect(callback.bind(req))
	var err := req.request(url)
	if err != OK:
		callback.call(0, 0, PackedStringArray(), PackedByteArray(), req)

func _on_village(_result: int, code: int, _headers: PackedStringArray, body: PackedByteArray, req: HTTPRequest) -> void:
	if code == 200:
		var parsed = JSON.parse_string(body.get_string_from_utf8())
		if typeof(parsed) == TYPE_DICTIONARY:
			village = parsed
	req.queue_free()
	_done_request()

func _on_props(_result: int, code: int, _headers: PackedStringArray, body: PackedByteArray, req: HTTPRequest) -> void:
	if code == 200:
		var parsed = JSON.parse_string(body.get_string_from_utf8())
		if typeof(parsed) == TYPE_DICTIONARY and parsed.has("props") and typeof(parsed.props) == TYPE_ARRAY:
			props_data = parsed.props
	req.queue_free()
	_done_request()

func _done_request() -> void:
	requests_left -= 1
	if requests_left > 0:
		return
	if village.is_empty():
		village = _sample_village()
		props_data = []
	# Only rebuild when something actually moved: the island is regenerated from the seed
	# and that is 60 ms of work, which is cheap once and wasteful five times a minute.
	var signature := _signature()
	if signature == last_signature:
		return
	last_signature = signature
	_rebuild()

func _signature() -> String:
	var island: Dictionary = village.get("island", {})
	return "%s|%s|%d|%d|%d|%d|%d|%d" % [
		str(island.get("terrainHash", "")), str(village.get("districtsRev", "")),
		(village.get("buildings", []) as Array).size(),
		(village.get("paths", []) as Array).size(),
		(village.get("bridges", []) as Array).size(),
		(village.get("cleared", []) as Array).size(),
		(village.get("polders", []) as Array).size(),
		props_data.size(),
	]

# ---- building the world -----------------------------------------------------

func _rebuild() -> void:
	var island: Dictionary = village.get("island", {})
	var seed_number := int(island.get("seed", 1337))
	var grid_size := int((village.get("grid", {}) as Dictionary).get("size", 64))
	var polders: Array = village.get("polders", [])

	var t0 := Time.get_ticks_msec()
	terrain = PmTerrain.new(seed_number, grid_size, polders)
	var terrain_ms := Time.get_ticks_msec() - t0

	var expected := str(island.get("terrainHash", ""))
	var agrees := expected == "" or expected == terrain.hash_hex
	if not agrees:
		push_warning("Terrain hash %s does not match the server's %s" % [terrain.hash_hex, expected])

	t0 = Time.get_ticks_msec()
	_build_ground()
	_build_water()
	_build_objects()
	var draw_ms := Time.get_ticks_msec() - t0

	var name_text := str(island.get("name", "Promptholm"))
	var line := "%s - %d buildings, %d props, %d rivers, %d bridges" % [
		name_text, (village.get("buildings", []) as Array).size(), props_data.size(),
		terrain.rivers.size(), (village.get("bridges", []) as Array).size()]
	var check := "terrain %s ok" % terrain.hash_hex if agrees else "TERRAIN MISMATCH %s != %s" % [terrain.hash_hex, expected]
	status.text = "%s\n%s - built in %d ms, drawn in %d ms" % [line, check, terrain_ms, draw_ms]
	print(status.text)

# Height of the drawn surface at a world position, so props and houses stand on the same
# ground the eye sees. What is land and what is water still comes from the terrain -- only
# the exact height is taken from here.
func _render_height(x: float, z: float) -> float:
	if _fine_cols == 0:
		return terrain.world_height(x, z) if terrain != null else 0.0
	var fx := clampf((x + terrain.half) / _fine_step, 0.0, _fine_cols - 1.0001)
	var fz := clampf((z + terrain.half) / _fine_step, 0.0, _fine_cols - 1.0001)
	var i := int(fx)
	var j := int(fz)
	var u := fx - i
	var v := fz - j
	var h00 := _fine[i + j * _fine_cols]
	var h10 := _fine[i + 1 + j * _fine_cols]
	var h01 := _fine[i + (j + 1) * _fine_cols]
	var h11 := _fine[i + 1 + (j + 1) * _fine_cols]
	return lerpf(lerpf(h00, h10, u), lerpf(h01, h11, u), v)

func _cell_height(gx: int, gz: int) -> float:
	var w := terrain.cell_world(gx, gz)
	return _render_height(w.x, w.y)

func _season_name() -> String:
	var month := int(Time.get_datetime_dict_from_system().month) - 1
	if month <= 1 or month == 11:
		return "winter"
	if month <= 4:
		return "spring"
	if month <= 7:
		return "summer"
	return "autumn"

func _band_colour(h: float, season: Dictionary) -> Color:
	if h < -0.6:
		return Color8(0x3f, 0x6a, 0x7c)
	if h < 0.0:
		return Color8(0x8f, 0x9f, 0x7a)
	if h < 0.35:
		return Color8(0xef, 0xdd, 0xb2)
	if h < 1.6:
		return season.meadow
	if h < 3.4:
		return season.upland
	if h < 5.2:
		return Color8(0x8f, 0x8a, 0x80)
	return season.summit

# The ground is drawn finer than the grid it comes from. A cell is a world unit and the
# layout thinks in whole cells, but nothing says the mesh has to: sampling world_height()
# between the corners gives the same surface with a smoother silhouette, and costs only
# triangles. The subdivision drops back on a bigger grid so the vertex count stays put.
const MAX_GROUND_VERTS := 40000

func _ground_subdiv() -> int:
	var k := 4
	while k > 1 and (terrain.size * k + 1) * (terrain.size * k + 1) > MAX_GROUND_VERTS:
		k -= 1
	return k

func _build_ground() -> void:
	_clear(ground_root)
	var season: Dictionary = SEASONS[_season_name()]
	var meadow := PmSimplex.new(PmRng.hash32("meadow:" + str(terrain.island_seed)))
	var k := _ground_subdiv()
	var step := 1.0 / k
	var cols := terrain.size * k + 1
	var count := cols * cols

	var heights := PackedFloat32Array()
	heights.resize(count)
	var verts := PackedVector3Array()
	verts.resize(count)
	var colours := PackedColorArray()
	colours.resize(count)
	for j in cols:
		for i in cols:
			var x := -terrain.half + i * step
			var z := -terrain.half + j * step
			var h := terrain.world_height(x, z)
			var idx := i + j * cols
			heights[idx] = h
			verts[idx] = Vector3(x, h, z)
			var col := _band_colour(h, season)
			if h >= 0.35 and h < 3.4:
				var m := 1.0 + meadow.noise2(x * 0.12, z * 0.12) * 0.065
				col = Color(minf(col.r * m, 1.0), minf(col.g * m, 1.0), minf(col.b * m, 1.0))
			colours[idx] = col

	# Sampling finer does not by itself look better: bilinear over a quantised field just
	# shows every terrace the carving left. A couple of blur passes take those out. The
	# waterline is held where it was -- a vertex may not cross sea level -- because moving
	# it would drown coast the layout calls land.
	for pass_index in 2:
		var blurred := PackedFloat32Array()
		blurred.resize(count)
		for j in cols:
			for i in cols:
				var sum := 0.0
				var n := 0
				for dj in range(-1, 2):
					var jj := j + dj
					if jj < 0 or jj >= cols:
						continue
					for di in range(-1, 2):
						var ii := i + di
						if ii < 0 or ii >= cols:
							continue
						sum += heights[ii + jj * cols]
						n += 1
				var idx2 := i + j * cols
				var v := sum / n
				if heights[idx2] >= 0.0:
					v = maxf(v, 0.0)
				else:
					v = minf(v, -0.002)
				blurred[idx2] = v
		heights = blurred
	for j in cols:
		for i in cols:
			var idx3 := i + j * cols
			var h3 := heights[idx3]
			var v3 := verts[idx3]
			verts[idx3] = Vector3(v3.x, h3, v3.z)
			var col3 := _band_colour(h3, season)
			if h3 >= 0.35 and h3 < 3.4:
				var m3 := 1.0 + meadow.noise2(v3.x * 0.12, v3.z * 0.12) * 0.065
				col3 = Color(minf(col3.r * m3, 1.0), minf(col3.g * m3, 1.0), minf(col3.b * m3, 1.0))
			colours[idx3] = col3
	_fine = heights
	_fine_cols = cols
	_fine_step = step

	# Normals straight off the heightfield: cheaper than accumulating face normals, and on
	# a grid of samples it is the same answer.
	var normals := PackedVector3Array()
	normals.resize(count)
	for j in cols:
		for i in cols:
			var xa := heights[maxi(i - 1, 0) + j * cols]
			var xb := heights[mini(i + 1, cols - 1) + j * cols]
			var za := heights[i + maxi(j - 1, 0) * cols]
			var zb := heights[i + mini(j + 1, cols - 1) * cols]
			normals[i + j * cols] = Vector3(xa - xb, 2.0 * step, za - zb).normalized()

	var quads := cols - 1
	var indices := PackedInt32Array()
	indices.resize(quads * quads * 6)
	var at := 0
	for j in quads:
		for i in quads:
			var a := i + j * cols
			var b := a + 1
			var c := a + cols
			var d := c + 1
			indices[at] = a
			indices[at + 1] = b
			indices[at + 2] = c
			indices[at + 3] = b
			indices[at + 4] = d
			indices[at + 5] = c
			at += 6

	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_COLOR] = colours
	arrays[Mesh.ARRAY_INDEX] = indices
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	var mi := MeshInstance3D.new()
	mi.name = "Island"
	mi.mesh = mesh
	mi.material_override = materials.ground
	ground_root.add_child(mi)

# One surface for all the water there is: sea, lake and rivers all sit under this plane
# and the ground hides it everywhere else. Shading it by the depth of the ground beneath
# is what makes a river read as a river rather than as a blue stripe.
func _build_water() -> void:
	_clear(water_root)
	var span := terrain.size + 80
	var half_span := span / 2.0
	var cols := span + 1
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for j in cols:
		for i in cols:
			var x := -half_span + i
			var z := -half_span + j
			var depth := -2.5
			if absf(x) <= terrain.half and absf(z) <= terrain.half:
				depth = _render_height(x, z)
			var t := clampf(-depth / 2.2, 0.0, 1.0)
			var col := Color8(0x6e, 0xa8, 0xb2).lerp(Color8(0x0b, 0x2a, 0x40), t)
			col.a = lerpf(0.42, 0.93, t)
			st.set_color(col)
			st.add_vertex(Vector3(x, 0.0, z))
	for j in span:
		for i in span:
			var a := i + j * cols
			var b := a + 1
			var c := a + cols
			var d := c + 1
			st.add_index(a)
			st.add_index(b)
			st.add_index(c)
			st.add_index(b)
			st.add_index(d)
			st.add_index(c)
	st.generate_normals()
	# The detailed grid only reaches a little past the coast; beyond it a plain slab of
	# deep water carries the horizon, so the sea does not end in a visible square edge.
	var far := MeshInstance3D.new()
	far.name = "Ocean"
	var far_mesh := PlaneMesh.new()
	far_mesh.size = Vector2(4000, 4000)
	far.mesh = far_mesh
	far.position = Vector3(0, -0.06, 0)
	far.material_override = materials.ocean
	water_root.add_child(far)

	var mi := MeshInstance3D.new()
	mi.name = "Sea"
	mi.mesh = st.commit()
	mi.material_override = materials.water
	water_root.add_child(mi)

# ---- what stands on the island ----------------------------------------------

const TIER_HEIGHT := {
	"tent": 0.85, "hut": 1.05, "cottage": 1.45, "house": 1.85,
	"manor": 2.6, "shed": 0.7, "civic": 2.3,
}

func _build_objects() -> void:
	_clear(objects_root)
	_build_cells(village.get("cleared", []), materials.paved, 0.02, 0.92)
	_build_paths()
	_build_bridges()
	_build_districts()
	_build_buildings()
	_build_props()

func _build_cells(cells: Array, mat: Material, lift: float, footprint: float) -> void:
	for cell in cells:
		if typeof(cell) != TYPE_ARRAY or (cell as Array).size() < 2:
			continue
		var gx := int(cell[0])
		var gz := int(cell[1])
		if not terrain.in_grid(gx, gz):
			continue
		var w := terrain.cell_world(gx, gz)
		var y := _cell_height(gx, gz) + lift
		_add_box(Vector3(w.x, y, w.y), Vector3(footprint, 0.04, footprint), mat)

# A road is one cell wide in the layout because that is the coarsest thing a route can
# be, not because a cart needs four metres. Drawing it as a ribbon down the middle of its
# cells keeps the route exactly where the layout put it and still looks like a lane.
const ROAD_WIDTH := 0.42

func _build_paths() -> void:
	for p in village.get("paths", []):
		var cells: Array = p.get("cells", [])
		for i in cells.size():
			var cell = cells[i]
			if typeof(cell) != TYPE_ARRAY or (cell as Array).size() < 2:
				continue
			var gx := int(cell[0])
			var gz := int(cell[1])
			if not terrain.in_grid(gx, gz):
				continue
			# The joint fills the inside of a turn, and sits a hair lower than the runs so
			# the two do not fight over the same pixels.
			var w := terrain.cell_world(gx, gz)
			_add_box(Vector3(w.x, _cell_height(gx, gz) + 0.038, w.y),
				Vector3(ROAD_WIDTH, 0.04, ROAD_WIDTH), materials.path)
			if i + 1 >= cells.size():
				continue
			var nxt = cells[i + 1]
			if typeof(nxt) != TYPE_ARRAY or (nxt as Array).size() < 2:
				continue
			var nx := int(nxt[0])
			var nz := int(nxt[1])
			if not terrain.in_grid(nx, nz) or absi(nx - gx) + absi(nz - gz) != 1:
				continue
			var b := terrain.cell_world(nx, nz)
			var mid := Vector3((w.x + b.x) * 0.5,
				(_cell_height(gx, gz) + _cell_height(nx, nz)) * 0.5 + 0.042, (w.y + b.y) * 0.5)
			var run := Vector3(1.0, 0.04, ROAD_WIDTH) if nz == gz else Vector3(ROAD_WIDTH, 0.04, 1.0)
			_add_box(mid, run, materials.path)

# A deck rides over what it crosses, so its height comes from the banks at either end --
# the same reasoning as bridgeDeck() in the browser: stopping at the water's edge would
# leave it hanging in mid-air over a valley whose lip is not land either.
func _build_bridges() -> void:
	for b in village.get("bridges", []):
		var cells: Array = b.get("cells", [])
		if cells.size() == 0:
			continue
		var along := Vector2i(1, 0) if str(b.get("axis", "x")) == "x" else Vector2i(0, 1)
		var first := Vector2i(int(cells[0][0]), int(cells[0][1]))
		var last := Vector2i(int(cells[cells.size() - 1][0]), int(cells[cells.size() - 1][1]))
		var bank_a := _cell_height(first.x - along.x, first.y - along.y)
		var bank_b := _cell_height(last.x + along.x, last.y + along.y)
		var deck_y := maxf(maxf(bank_a, bank_b), 0.0) + 0.3
		var across := Vector2i(along.y, along.x)
		for cell in cells:
			var gx := int(cell[0])
			var gz := int(cell[1])
			var w := terrain.cell_world(gx, gz)
			_add_box(Vector3(w.x, deck_y, w.y), Vector3(1.0, 0.12, 1.0), materials.deck)
			for side: int in [-1, 1]:
				var rx := w.x + across.x * 0.46 * side
				var rz := w.y + across.y * 0.46 * side
				var rail_size := Vector3(0.08 if across.x != 0 else 1.0, 0.34, 0.08 if across.y != 0 else 1.0)
				_add_box(Vector3(rx, deck_y + 0.23, rz), rail_size, materials.rail)

func _build_districts() -> void:
	for d in village.get("districts", []):
		var c = d.get("center", null)
		if typeof(c) != TYPE_ARRAY or (c as Array).size() < 2:
			continue
		var gx := int(c[0])
		var gz := int(c[1])
		var w := terrain.cell_world(gx, gz)
		var y := _cell_height(gx, gz)
		var hue := float(d.get("hue", 200)) / 360.0
		var mat := _mat(Color.from_hsv(hue, 0.45, 0.85))
		_add_cylinder(Vector3(w.x, y + 0.08, w.y), 0.5, 0.16, mat)
		_add_label(str(d.get("name", "district")), Vector3(w.x, y + 1.1, w.y), 22)

func _build_buildings() -> void:
	var active := {}
	for id in village.get("active", []):
		active[str(id)] = true
	for b in village.get("buildings", []):
		var plot = b.get("plot", null)
		if typeof(plot) != TYPE_DICTIONARY:
			continue
		var gx := float(plot.get("gx", 32))
		var gz := float(plot.get("gz", 32))
		var pw := float(plot.get("w", 1))
		var pd := float(plot.get("d", 1))
		var rot := int(plot.get("rot", 0))
		var x := gx + pw * 0.5 - terrain.half
		var z := gz + pd * 0.5 - terrain.half
		var ground := _render_height(x, z)
		var kind := str(b.get("kind", "house"))
		var tier := str(b.get("tier", kind))
		var body_h: float = TIER_HEIGHT.get(tier, 1.4)
		var fw := maxf(0.55, pw * 0.72)
		var fd := maxf(0.55, pd * 0.72)
		var wall_mat: Material = materials.wall
		var roof_mat: Material = materials.roof
		if kind == "civic":
			wall_mat = materials.civic_wall
			roof_mat = materials.civic_roof
		elif kind == "shed":
			wall_mat = materials.shed
			roof_mat = materials.shed_roof

		if tier == "tent":
			_add_cone(Vector3(x, ground, z), maxf(fw, fd) * 0.62, body_h, roof_mat)
		else:
			_add_box(Vector3(x, ground + body_h * 0.5, z), Vector3(fw, body_h, fd), wall_mat)
			var roof_h := 0.36 + 0.14 * maxf(fw, fd)
			var roof := MeshInstance3D.new()
			var prism := PrismMesh.new()
			prism.size = Vector3(fw * 1.08, roof_h, fd * 1.08)
			roof.mesh = prism
			roof.position = Vector3(x, ground + body_h + roof_h * 0.5, z)
			roof.rotation = Vector3(0, PI * 0.5 * rot, 0)
			roof.material_override = roof_mat
			objects_root.add_child(roof)

		if active.has(str(b.get("id", ""))) or bool(b.get("active", false)):
			_add_sphere(Vector3(x, ground + body_h + 0.95, z), 0.16, materials.active)
		if kind == "civic":
			var label := str(b.get("label", b.get("name", "")))
			if label != "":
				_add_label(label, Vector3(x, ground + body_h + 0.75, z), 18)

func _build_props() -> void:
	for p in props_data:
		var x := float(p.get("x", 0.0))
		var z := float(p.get("z", 0.0))
		var scale := float(p.get("scale", 1.0))
		var y := _render_height(x, z)
		match str(p.get("kind", "prop")):
			"tree", "pine":
				_add_cylinder(Vector3(x, y + 0.3 * scale, z), 0.1 * scale, 0.6 * scale, materials.trunk)
				_add_cone(Vector3(x, y + 0.55 * scale, z), 0.42 * scale, 1.1 * scale, materials.leaf)
			"lamp":
				_add_cylinder(Vector3(x, y + 0.4 * scale, z), 0.06 * scale, 0.8 * scale, materials.dark)
				_add_sphere(Vector3(x, y + 0.88 * scale, z), 0.14 * scale, materials.lamp)
			"panel":
				var length := 1.5
				if p.get("length", null) != null:
					length = float(p.get("length"))
				var post_h := 0.7 * scale
				_add_box(Vector3(x, y + post_h * 0.5, z), Vector3(0.09, post_h, 0.09), materials.dark)
				var board := MeshInstance3D.new()
				var bm := BoxMesh.new()
				bm.size = Vector3(length * scale, 0.85 * scale, 0.07)
				board.mesh = bm
				board.position = Vector3(x, y + post_h + 0.42 * scale, z)
				board.rotation = Vector3(0, float(p.get("rot", 0.0)), 0)
				board.material_override = materials.panel
				objects_root.add_child(board)
				var text := str(p.get("label", "")) if p.get("label", null) != null else ""
				if text != "":
					_add_label(text, Vector3(x, y + post_h + 1.05 * scale, z), 16)
			_:
				_add_box(Vector3(x, y + 0.18, z), Vector3(0.36, 0.36, 0.36), materials.civic_wall)

# queue_free() only takes effect at the end of the frame, so a rebuild that simply
# queued the old island would draw both of them over each other until then.
func _clear(node: Node) -> void:
	for c in node.get_children():
		node.remove_child(c)
		c.queue_free()

# ---- primitives -------------------------------------------------------------

func _add_box(pos: Vector3, box_size: Vector3, mat: Material) -> MeshInstance3D:
	var n := MeshInstance3D.new()
	var mesh := BoxMesh.new()
	mesh.size = box_size
	n.mesh = mesh
	n.position = pos
	n.material_override = mat
	objects_root.add_child(n)
	return n

func _add_cylinder(pos: Vector3, radius: float, height: float, mat: Material) -> MeshInstance3D:
	var n := MeshInstance3D.new()
	var mesh := CylinderMesh.new()
	mesh.top_radius = radius
	mesh.bottom_radius = radius
	mesh.height = height
	n.mesh = mesh
	n.position = pos
	n.material_override = mat
	objects_root.add_child(n)
	return n

func _add_cone(base: Vector3, radius: float, height: float, mat: Material) -> MeshInstance3D:
	var n := MeshInstance3D.new()
	var mesh := CylinderMesh.new()
	mesh.top_radius = 0.0
	mesh.bottom_radius = radius
	mesh.height = height
	n.mesh = mesh
	n.position = base + Vector3(0, height * 0.5, 0)
	n.material_override = mat
	objects_root.add_child(n)
	return n

func _add_sphere(pos: Vector3, radius: float, mat: Material) -> MeshInstance3D:
	var n := MeshInstance3D.new()
	var mesh := SphereMesh.new()
	mesh.radius = radius
	mesh.height = radius * 2.0
	n.mesh = mesh
	n.position = pos
	n.material_override = mat
	objects_root.add_child(n)
	return n

func _add_label(text: String, pos: Vector3, font_size: int) -> void:
	var label := Label3D.new()
	label.text = text
	label.font_size = font_size
	label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	label.outline_size = 6
	label.pixel_size = 0.006
	label.modulate = Color(0.96, 0.98, 0.92)
	label.position = pos
	objects_root.add_child(label)

# Enough of an island to show something when the Node server is not running.
func _sample_village() -> Dictionary:
	return {
		"island": { "name": "Sample Promptholm", "seed": 1337, "terrainHash": "" },
		"grid": { "size": 64 },
		"cleared": [[31, 26], [32, 26], [31, 27], [32, 27]],
		"paths": [{ "cells": [[32, 29], [32, 30], [32, 31]] }],
		"districts": [],
		"buildings": [
			{ "kind": "civic", "tier": "civic", "label": "Town Hall", "plot": { "gx": 31, "gz": 26, "w": 3, "d": 3, "rot": 2 } },
		],
		# A real crossing of the seed-1337 river, so the offline view shows a deck too.
		"bridges": [{ "id": "bridge:sample", "axis": "x", "cells": [[39, 50], [40, 50], [41, 50], [42, 50]] }],
		"polders": [],
		"active": [],
	}
